version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      retries: 5

  web:
    build: ./web
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://myuser:mypass@db:5432/mydb
    depends_on:
      db:
        condition: service_healthy
